name : Merge Data
on :
  workflow_dispatch:
    
jobs:
  crawling:
    runs-on: ubuntu-latest
    steps:
    - name: check out repository
      uses: actions/checkout@v1
    
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    
    - name: get_data
      run: |
        git config --global user.email 1978633500@qq.com
        git config --global user.name kaleidoscope
        cd ${{github.workspace}}
        git clone git@github.com:kal-eido-scope/new_hole_crawler_pg_2.0.git
        git clone git@github.com:kal-eido-scope/new_hole_crawler_2.0.git
      
    - name: merge
      run: |
        python merge_diff.py

    - name: Get Time
      id : time
      uses: josStorer/get-current-time@v2.0.0
      with:
        utcOffset: "+08:00"

    - name: git_add
      run: |
        git add .
        git commit -m "Crawl_${{steps.time.outputs.readableTime}}"

    - name: git_push
      uses: ad-m/github-push-action@master
      with: 
        github_token: ${{secrets.ACCESS_TOKEN}}
 
